version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data-volumes/postgres/:/var/lib/postgresql/data/
  liquibase:
    image: webdevops/liquibase:postgres
    restart: 'no'
    depends_on:
      - postgres
    volumes:
      - ./docker/:/liquibase/