version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data-volumes/postgres/:/var/lib/postgresql/data/
  liquibase:
    image: webdevops/liquibase:postgres
    restart: 'no'
    depends_on:
      - postgres
    volumes:
    - ./liquibase/:/liquibase/
    environment:
      - LIQUIBASE_URL=jdbc:postgresql://postgres:5432/users
      - LIQUIBASE_USERNAME=postgres
      - LIQUIBASE_PASSWORD=postgres
      - LIQUIBASE_CHANGELOG=/liquibase/changelog.xml
    command:
      - update